# Generated by Django 3.1.2 on 2022-06-23 06:18

from django.db import migrations, models
import visualizer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cas_rn', models.CharField(blank=True, max_length=12, null=True, verbose_name='CAS Registry Number')),
                ('compound_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Compound Name')),
                ('classification', models.JSONField(blank=True, default=visualizer.models.classification_default, null=True, verbose_name='Classification')),
                ('synonyms', models.JSONField(blank=True, default=list, null=True, verbose_name='Synonyms')),
                ('inchi', models.TextField(blank=True, unique=True, verbose_name='InChI')),
                ('smiles', models.TextField(blank=True, default='', verbose_name='SMILES')),
                ('exact_mass', models.FloatField(default=0, editable=False, verbose_name='Exact Mass')),
                ('inchikey', models.CharField(default='', editable=False, max_length=27, unique=True, verbose_name='InChIKey')),
                ('formula', models.CharField(default='', editable=False, max_length=255, verbose_name='Molecular Formula')),
                ('icon_2dsvg', models.TextField(default='', editable=False, verbose_name='SVG Icon')),
                ('structure_2dsvg', models.TextField(default='', editable=False, verbose_name='2D Chemical Structure')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Update Date')),
            ],
            options={
                'verbose_name': 'Compound',
                'verbose_name_plural': 'Compound',
            },
        ),
    ]
