# Generated by Django 3.1.2 on 2022-06-23 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='classification',
        ),
        migrations.CreateModel(
            name='Classyfire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kingdom', models.CharField(blank=True, max_length=20, null=True, verbose_name='Kingdom')),
                ('superclass', models.CharField(blank=True, max_length=20, null=True, verbose_name='Superclass')),
                ('chem_class', models.CharField(blank=True, max_length=20, null=True, verbose_name='Class')),
                ('subclass', models.CharField(blank=True, max_length=20, null=True, verbose_name='Subclass')),
                ('direct_parent', models.CharField(blank=True, max_length=20, null=True, verbose_name='Direct Parent')),
                ('compound', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classyfire', to='visualizer.compound', verbose_name='Compound ID')),
            ],
        ),
    ]
